# Generated by Django 2.2.2 on 2019-06-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
