# Generated by Django 2.2.2 on 2019-06-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='department',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
