# Generated by Django 2.2.2 on 2019-06-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190621_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='teacher',
            field=models.CharField(default='Ashutosh', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='department',
            field=models.CharField(max_length=64),
        ),
    ]
