# Generated by Django 2.2.2 on 2019-06-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20190621_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='department',
            field=models.CharField(default='cse', max_length=64),
            preserve_default=False,
        ),
    ]
