# Generated by Django 2.2.2 on 2019-06-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20190621_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='teacher',
        ),
    ]
