# Generated by Django 2.2.2 on 2019-06-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20190621_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='department',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='notes',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
