# Generated by Django 2.2.2 on 2019-07-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20190721_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
