# Generated by Django 2.2.2 on 2019-08-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20190721_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
