# Generated by Django 2.2.2 on 2019-07-21 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seachquary',
            old_name='quary',
            new_name='query',
        ),
    ]
